FROM postgres:9.6

RUN apt-get update
RUN apt-get install -y git build-essential postgresql-server-dev-9.6 postgresql-client-9.6
RUN git clone https://github.com/r888888888/test_parser.git /tmp/test_parser
RUN cd /tmp/test_parser && make install
RUN rm -rf /tmp/test_parser
