development:
  adapter: postgresql
  database: db_instance_development
  host: <%= ENV["DB_INSTANCE_DEVELOPMENT_HOST"] %>
  username: <%= ENV["DB_INSTANCE_DEVELOPMENT_USER"] %>
  password: 
  port: 5432

test:
  adapter: postgresql
  database: db_instance_test
  host: <%= ENV["DB_INSTANCE_DEVELOPMENT_HOST"] %>
  username: <%= ENV["DB_INSTANCE_DEVELOPMENT_USER"] %>
  password: 
  port: 5432

production:
  adapter: postgresql
  database: db_instance_production
  host: <%= ENV["DB_INSTANCE_PRODUCTION_HOST"] %>
  username: <%= ENV["DB_INSTANCE_PRODUCTION_USER"] %>
  password: <%= ENV["DB_INSTANCE_PRODUCTION_PASSWORD"] %>
  port: 5432

core_development:
  adapter: postgresql
  database: db_core_development
  host: postgres
  username: postgres
  password: 
  port: 5432

core_test:
  adapter: postgresql
  database: db_core_test
  host: postgres
  username: postgres
  password: 
  port: 5432

core_production:
  adapter: postgresql
  database: db_core_production
  host: postgres
  username: postgres
  password: <%= ENV["DB_CORE_PRODUCTION_PASSWORD"] %>
  port: 5432

archive_development:
  adapter: postgresql
  database: db_archive_development
  host: <%= ENV["DB_INSTANCE_DEVELOPMENT_HOST"] %>
  username: <%= ENV["DB_INSTANCE_DEVELOPMENT_USER"] %>
  password: 
  port: 5432

archive_test:
  adapter: postgresql
  database: db_archive_test
  host: <%= ENV["DB_INSTANCE_DEVELOPMENT_HOST"] %>
  username: <%= ENV["DB_INSTANCE_DEVELOPMENT_USER"] %>
  password: 
  port: 5432

archive_production:
  adapter: postgresql
  database: db_archive_production
  host: postgres
  username: postgres
  password: <%= ENV["DB_ARCHIVE_PRODUCTION_PASSWORD"] %>
  port: 5432
