development:
  adapter: postgresql
  database: db_instance_development
  host: postgres
  username: postgres
  password: 
  port: 5432

test:
  adapter: postgresql
  database: db_instance_test
  host: postgres
  username: postgres
  password: 
  port: 5432

production:
  adapter: postgresql
  database: db_instance_development
  host: postgres
  username: postgres
  password: 
  port: 5432

core_development:
  adapter: postgresql
  database: db_core_development
  host: postgres
  username: postgres
  password: 
  port: 5432

core_test:
  adapter: postgresql
  database: db_core_test
  host: postgres
  username: postgres
  password: 
  port: 5432

core_production:
  adapter: postgresql
  database: db_core_development
  host: postgres
  username: postgres
  password: 
  port: 5432

archive_development:
  adapter: postgresql
  database: db_archive_development
  host: postgres
  username: postgres
  password: 
  port: 5432

archive_test:
  adapter: postgresql
  database: db_archive_test
  host: postgres
  username: postgres
  password: 
  port: 5432

archive_production:
  adapter: postgresql
  database: db_archive_development
  host: postgres
  username: postgres
  password: 
  port: 5432
